create table bet (id bigint not null auto_increment, amount integer not null, bet_choice_user1 integer, bet_choice_user2 integer, result integer not null, status varchar(255), match_id bigint, user1_id bigint, user2_id bigint, primary key (id)) engine=MyISAM;
create table confirmation_token (id bigint not null auto_increment, confirmed_at datetime, created_at datetime not null, expires_at datetime not null, token varchar(255) not null, user_id bigint not null, primary key (id)) engine=MyISAM;
create table league (id bigint not null auto_increment, country varchar(255), name varchar(255), sport_id bigint, primary key (id)) engine=MyISAM;
create table league_matches (league_id bigint not null, matches_id bigint not null, primary key (league_id, matches_id)) engine=MyISAM;
create table league_teams (league_id bigint not null, teams_id bigint not null, primary key (league_id, teams_id)) engine=MyISAM;
create table match_entity (id bigint not null auto_increment, data varchar(255), is_upcoming bit not null, result varchar(255), start_time datetime, league_id bigint, team1_id bigint, team2_id bigint, primary key (id)) engine=MyISAM;
create table sport (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=MyISAM;
create table sport_leagues (sport_id bigint not null, leagues_id bigint not null, primary key (sport_id, leagues_id)) engine=MyISAM;
create table team (id bigint not null auto_increment, country varchar(255), name varchar(255), primary key (id)) engine=MyISAM;
create table team_matches (team_id bigint not null, matches_id bigint not null, primary key (team_id, matches_id)) engine=MyISAM;
create table user (id bigint not null auto_increment, wallet integer not null, confirmed bit, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), role varchar(255), username varchar(255), primary key (id)) engine=MyISAM;
create table user_bets (user_id bigint not null, bets_id bigint not null, primary key (user_id, bets_id)) engine=MyISAM;
create table user_favorite_leagues (user_id bigint not null, favorite_leagues_id bigint not null, primary key (user_id, favorite_leagues_id)) engine=MyISAM;
create table user_favorite_matches (user_id bigint not null, favorite_matches_id bigint not null, primary key (user_id, favorite_matches_id)) engine=MyISAM;
create table user_favorite_teams (user_id bigint not null, favorite_teams_id bigint not null, primary key (user_id, favorite_teams_id)) engine=MyISAM;
create table user_friends (user_id bigint not null, friends_id bigint not null, primary key (user_id, friends_id)) engine=MyISAM;
alter table league_matches add constraint UK_bw2qjvedqigcjdxmu2hq9e8sa unique (matches_id);
    alter table league_teams add constraint UK_rdfn86g37n356sf9l8vep4f76 unique (teams_id);
    alter table sport_leagues add constraint UK_fplrrpcs9ncrlyw6nygky2g0s unique (leagues_id);
    alter table team_matches add constraint UK_ca2prqkp1fs3h2l49re9ytvgt unique (matches_id);
    alter table user_favorite_leagues add constraint UK_lhko7iqf4rt6q9b2sauq33cc1 unique (favorite_leagues_id);
    alter table user_favorite_matches add constraint UK_am7rd7iu9t37a52dfw9wtc5e5 unique (favorite_matches_id);
    alter table user_favorite_teams add constraint UK_elhl0b0fk583yu2sviv792ghr unique (favorite_teams_id);
    alter table bet add constraint FK6okt30geuvye4va3y2dctwcs2 foreign key (match_id) references match_entity (id);
    alter table bet add constraint FK115n3uho26unht09309t5fw80 foreign key (user1_id) references user (id);
    alter table bet add constraint FKe7ucumi746eukm7rwg65qe3oc foreign key (user2_id) references user (id);
    alter table confirmation_token add constraint FKhjrtky9wbd6lbk7mu9tuddqgn foreign key (user_id) references user (id);
    alter table league add constraint FK11gkb0t51knp0pqxryy274iaw foreign key (sport_id) references sport (id);
    alter table league_matches add constraint FKe5yc0ijqv2bbxbp22bko1171w foreign key (matches_id) references match_entity (id);
    alter table league_matches add constraint FKbli33wr6ag0k72abj073tgqwf foreign key (league_id) references league (id);
    alter table league_teams add constraint FK346p2kjh3ajaw1ia5vie3q11n foreign key (teams_id) references team (id);
    alter table league_teams add constraint FKead30uj0lm051cu5ch04wjtxi foreign key (league_id) references league (id);
    alter table match_entity add constraint FKnu3auj5ptltmktbhb2n7ect24 foreign key (league_id) references league (id);
    alter table match_entity add constraint FKm9mttyiibvk7hd91y56iwt431 foreign key (team1_id) references team (id);
    alter table match_entity add constraint FK1hapjugyi8g527gjv5cs3qt8d foreign key (team2_id) references team (id);
    alter table sport_leagues add constraint FKd7unnnf2kc4scytsvkoklr19y foreign key (leagues_id) references league (id);
    alter table sport_leagues add constraint FKsbnxwryiqx830liyo2pc2f0dm foreign key (sport_id) references sport (id);
    alter table team_matches add constraint FKbx9w4c2gdh1kuhs8wtk2bi89p foreign key (matches_id) references match_entity (id);
    alter table team_matches add constraint FKd9dx2hnof5j3nkoh6qvo78ok8 foreign key (team_id) references team (id);
    alter table user_bets add constraint FKtd4469rwpg7c6kxs5ww6kee7j foreign key (bets_id) references bet (id);
    alter table user_bets add constraint FK9xv5d9by1r6j1vhnmr5nj63vh foreign key (user_id) references user (id);
    alter table user_favorite_leagues add constraint FK734rgdloln6ulu9xcsrsfhdvw foreign key (favorite_leagues_id) references league (id);
    alter table user_favorite_leagues add constraint FKav9svv3lmud1dfv24j2e7w1rn foreign key (user_id) references user (id);
    alter table user_favorite_matches add constraint FK3mbgffvf4vgnovkbtvn1837l1 foreign key (favorite_matches_id) references match_entity (id);
    alter table user_favorite_matches add constraint FKia91w4rx4vebwbtbh6pi9ax76 foreign key (user_id) references user (id);
    alter table user_favorite_teams add constraint FKetu7qq4cw9j210n9rqvsm20f5 foreign key (favorite_teams_id) references team (id);
    alter table user_favorite_teams add constraint FKs3tifbk98jtsf7nepn1eq6yg foreign key (user_id) references user (id);
    alter table user_friends add constraint FKe1jhkryq5denjdrjngi7lj9h4 foreign key (friends_id) references user (id);
    alter table user_friends add constraint FK9i7cldnk7cx2g47qex8ovm2ah foreign key (user_id) references user (id);